# Generated by Django 6.0.2 on 2026-02-25 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=3, unique=True)),
                ('team', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('regulations', models.TextField(help_text='Technical regulations description')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('round_number', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='f1hub.season')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('season', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FP1', 'Free Practice 1'), ('FP2', 'Free Practice 2'), ('FP3', 'Free Practice 3'), ('Qualifying', 'Qualifying'), ('Sprint Shootout', 'Sprint Shootout'), ('Sprint', 'Sprint'), ('Race', 'Race')], max_length=50)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='f1hub.event')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Local path to the generated plot or data file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_driver1', to='f1hub.driver')),
                ('driver2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_driver2', to='f1hub.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_caches', to='f1hub.session')),
            ],
        ),
    ]
